[project]
name = "spatialexperiment"
dynamic = [
    "version",
]
description = "Container class for storing data from spatial-omics experiments"
readme = "README.md"
authors = [
    { name = "Jayaram Kancherla", email = "jayaram.kancherla@gmail.com" },
]
requires-python = ">=3.9"
keywords = [
    "bioinformatics",
    "spatial-omics",
    "spatial-transcriptomics",
    "single-cell",
    "bioconductor",
    "singlecellexperiment",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Typing :: Typed",
]
dependencies = [
    "biocframe>=0.7.2",
    "biocutils>=0.3.3",
    "singlecellexperiment>=0.6.0",
    "pillow>=11.0",
    "requests",
    "scipy~=1.13",
    "rasterio",
]


[project.license]
file = "LICENSE.txt"


[project.urls]
Homepage = "https://github.com/BiocPy/spatialexperiment"
Documentation = "https://biocpy.github.io/spatialexperiment/"
Source = "https://github.com/BiocPy/spatialexperiment"
"Bug Tracker" = "https://github.com/BiocPy/spatialexperiment/issues"

[project.optional-dependencies]
optional = [
    "anndata",
    "delayedarray",
    "pandas",
]
testing = [
    "anndata",
    "delayedarray",
    "pandas",
    "pytest",
    "pytest-cov",
]

[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.1.0"

[tool.ruff]
line-length = 120
src = [
    "src",
]
exclude = [
    "tests",
    "docs",
]

[tool.ruff.lint]
extend-ignore = [
    "F821",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "E402",
    "F401",
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20

[tool.mypy]
strict = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report term-missing"
testpaths = [
    "tests",
]

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B110"]
